Set-AzContext -Subscription "DevTest-BTDTS"
Start-AzVM -name "Dev5DC1" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5BTMNCON" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5BTMNWKR1" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5BTUsr1" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5CMN1" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5DOM9C" -ResourceGroupName "dev5-rg"
Start-AzVM -name "Dev5DOM9M" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5Exch01" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5IIS" -ResourceGroupName "dev5-rg"
Start-AzVM -name "Dev5MNE1" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5MNE2" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5MNE3" -ResourceGroupName "dev5-rg"
Start-AzVM -name "Dev5MNE4" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5MNEUsr1" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5MNEUsr2" -ResourceGroupName "dev5-rg"
#Start-AzVM -name "Dev5SQL1" -ResourceGroupName "dev5-rg"